use anyhow::Result;
use serde::{Deserialize, Serialize};
use std::fs;
use std::path::{Path, PathBuf};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Config {
	pub site: SiteConfig,
	pub navigation: NavigationConfig,
	pub theme: ThemeConfig,
	pub search: SearchConfig,
	pub export: ExportConfig,
	#[serde(default)]
	pub plugins: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SiteConfig {
	pub title: String,
	pub description: String,
	pub author: Option<String>,
	pub base_url: Option<String>,
	#[serde(default)]
	pub versions: Vec<String>,
	pub default_version: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NavigationConfig {
	#[serde(default)]
	pub sidebar: SidebarConfig,
	#[serde(default)]
	pub breadcrumbs: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct SidebarConfig {
	#[serde(default = "default_true")]
	pub enabled: bool,
	#[serde(default = "default_true")]
	pub auto_generate: bool,
	pub custom_order: Option<Vec<String>>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ThemeConfig {
	pub default_theme: Option<String>,       // "light" or "dark"
	pub syntax_highlighting: Option<String>, // "prism" or "highlight"
	pub custom_css: Option<PathBuf>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SearchConfig {
	#[serde(default = "default_true")]
	pub enabled: bool,
	pub engine: Option<String>, // "fuse" or "lunr"
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExportConfig {
	#[serde(default = "default_true")]
	pub html: bool,
	#[serde(default)]
	pub pdf: bool,
	#[serde(default)]
	pub man: bool,
}

fn default_true() -> bool {
	true
}

impl Default for Config {
	fn default() -> Self {
		Config {
			site: SiteConfig {
				title: "Rum".to_string(),
				description: "Documentation generated by Rum".to_string(),
				author: None,
				base_url: None,
				versions: vec!["latest".to_string()],
				default_version: Some("latest".to_string()),
			},
			navigation: NavigationConfig {
				sidebar: SidebarConfig {
					enabled: true,
					auto_generate: true,
					custom_order: None,
				},
				breadcrumbs: true,
			},
			theme: ThemeConfig {
				default_theme: Some("dark".to_string()),
				syntax_highlighting: Some("prism".to_string()),
				custom_css: None,
			},
			search: SearchConfig {
				enabled: true,
				engine: Some("fuse".to_string()),
			},
			export: ExportConfig {
				html: true,
				pdf: false,
				man: false,
			},
			plugins: vec![],
		}
	}
}

impl Config {
	pub fn load(path: Option<&Path>) -> Result<Self> {
		let default_config = Config::default();

		if let Some(config_path) = path {
			if config_path.exists() {
				let content = fs::read_to_string(config_path)?;
				let config: Config = toml::from_str(&content)?;
				return Ok(config);
			}
		}

		// Try to find rum.toml in current directory
		let current_dir = std::env::current_dir()?;
		let config_path = current_dir.join("rum.toml");

		if config_path.exists() {
			let content = fs::read_to_string(&config_path)?;
			let config: Config = toml::from_str(&content)?;
			return Ok(config);
		}

		Ok(default_config)
	}

	pub fn save(&self, path: &Path) -> Result<()> {
		let toml = toml::to_string_pretty(self)?;
		fs::write(path, toml)?;
		Ok(())
	}
}
